name: Deploy React via SSH and Docker Compose

# Pemicu workflow -> dijalankan saat ada push ke branch main atau bisa dijalankan manual
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # perintah untuk pull, rebuild dan migrasi
      - name: Connect to server, pull code, and rebuild docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CI_CD_SERVER_2 }}
          username: ${{ secrets.CI_CD_USER }}
          key: ${{ secrets.CI_CD_PASSWORD }}
          script: |
            cd /opt/production/scit/FE_Website
            git pull origin main
            sudo docker compose build --no-cache frontend
            echo "Build image finished successfully!"

            sudo docker compose up -d --force-recreate frontend

            echo "Deployment finished successfully!"